name = "vibecov-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "vibecov-db"
database_id = "" # Will be filled in after creating the database

# KV for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "" # Will be filled in after creating the namespace

# Environment variables (use wrangler secret for sensitive values)
[vars]
GITHUB_CALLBACK_URL = "http://localhost:8787/auth/callback"
FRONTEND_URL = "http://localhost:5173"

# Development overrides
[env.development]
vars = { GITHUB_CALLBACK_URL = "http://localhost:8787/auth/callback", FRONTEND_URL = "http://localhost:5173" }

# Production overrides
[env.production]
vars = { GITHUB_CALLBACK_URL = "https://api.vibecov.com/auth/callback", FRONTEND_URL = "https://vibecov.com" }
